# ==========================================================================
# ❗ The script runs relative to the project's root directory,
# gathers data from published sources (see the manuscript for references)
# and data generated by previous scripts and
# exports DAT_song_by_species.csv to ./DATA/.
# ==========================================================================

# Packages, settings (package sdb should be installed from https://github.com/mpio-be/sdb)
  source(here::here("R/__init__.R"))

  install_if_missing(
    c(
      "dplyr", "exactextractr", "fasterize", "ggplot2","lme4", "lwgeom", 'openxlsx',"rangeMapper", "rmapshaper", "qs",
      "raster", "tidygeocoder", "units", "dbo", "sf", "sfheaders", "stars"
    )
  )

# load taxa synonyms
  sy <- fread(here::here("Data/DAT_taxa_synonyms.csv")) # sy = dbq(q = 'select scinam , syid FROM AVES_taxonomy.synonyms_v2')
  # tax = dbq(q = 'select scinam, clade, family from AVES_taxonomy.birdtree')

# load traits
  load(here::here("Data/DAT_traits.Rdata")) # generaated by DAT_traits.R

# load breeding ranges
  con <- rmap_connect(path = here::here("Data/DAT_rangeMapper.sqlite")) # generated by DAT_rangeMapper.R
  br <- rmap_to_sf(con, "wkt_ranges")
  br <- mutate(br, scinam = str_replace(bio_id, "_", " ")) |> dplyr::select(-bio_id)
  dbDisconnect(con)

# load SONG
  x = fread(here::here("Data/song_raw.csv"))[!is.na(elements) & rec_quality_subj %in% c("A", "B")]
  x[, id := .I]

# add extrapolated number of element types (see Methods for details)
  x[, element_types_extrapol := 10^(log10(element_types) + 0.2644431 * (log10(50) - log10(elements)))]

# add missing coordinates and tree data
  trc = fread(here::here("Data/DAT_tree_cover.csv"))
  #trc = fread(here('DATA/DAT_tree_cover_v2-Global-2010.csv'))
  x = merge(x, trc, by = 'id', all.x = TRUE, sort = FALSE)

# compute species means
  d <-
    x[, .(
      element_types_mean = mean(element_types, na.rm = TRUE),
      element_types_extrapol_mean = mean(element_types_extrapol, na.rm = TRUE),
      elements_mean = mean(elements, na.rm = TRUE),
      N_recordings = as.numeric(.(.N)),
      latit = mean(lat, na.rm = TRUE),
      longit = mean (lon, na.rm = TRUE),
      altit = mean(altitude, na.rm = TRUE),
      tree_cover = mean(perc_forest, na.rm = TRUE)
    ), by = .(scinam, group, clade)]
  d[, id := .I]
  d[, scinam := str_replace(scinam, '_', ' ')]

# add central latitude and longitue of species breeding range
  lat_lon = fread("Data/DAT_range_center.csv") # generated by DAT_range_center.R
  lat_lon$pk = NULL
  d <- symerge(d, lat_lon, sy) # missing data for 3 species - d[is.na(lat), .(scinam)]

# for 3 species with missing ranges use mean lat/lon of recording
  # x[scinam %in% d[is.na(lat), scinam]] # no additional latitude data in lat/lon based on address
  d[is.na(lat), lat := latit]
  d[is.na(lon), lon := longit]
  d$latit <- d$longit <- NULL

# add mean altitude within species breeding range
  rr <- here::here("Data/_GMTED2010_eck4.tif") |> raster()
  br <- mutate(br, mean_sp_altitude = exact_extract(rr, br, fun = "mean"))
  alt <- data.table(br)[, .(scinam, mean_sp_altitude)]
  alt[mean_sp_altitude == 0, mean_sp_altitude := 1]
  d <- symerge(d, alt, sy)

# for 3 species with missing ranges use mean altitude of the recordings
  d[is.na(mean_sp_altitude), mean_sp_altitude := altit]
  d[is.na(lon), lon := longit]
  d$altit <- NULL

# add sex specific wing length from AVONET database
  w = fread(here::here("Data/_AVONET_Raw_Data.txt"))
  w[, scinam := tolower(Species3_BirdTree)]
  w[is.na(scinam), scinam := tolower(Species2_eBird)]
  w = w[!is.na(scinam)]
  w = w[!is.na(Wing.Length)]
  w = w[Sex %in% c("F", "M")]
  ws = w[, .(
     # N_values = as.numeric(.(.N)),
      wing_length = mean(Wing.Length)
      ), by = .(scinam, Sex)]
  wl <- dcast(ws, scinam ~ Sex, value.var = "wing_length")
  wl = wl[!is.na(F) & !is.na(M)]
  setnames(wl, c("M", "F"), c("male_wing_length_g", "female_wing_length_g"))
  d <- symerge(d, wl, sy)

# add species wing length from AVONET database
  # species means from AVONET
    wsp <- fread(here::here("Data/_AVONET3_BirdTree.txt"))
    wsp[, scinam := tolower(Species3)]
    wsp = wsp[, .(scinam, Wing.Length)]
    setnames(wsp, c('Wing.Length'), c('wing_length'))

  # species means recalculated from AVONETs individual values
    w = fread(here::here("Data/_AVONET_Raw_Data.txt"))
    w[, scinam := tolower(Species3_BirdTree)]
    w[is.na(scinam), scinam := tolower(Species2_eBird)]
    w = w[!is.na(scinam)]
    w = w[!is.na(Wing.Length)]
    ws <- w[, .(
      #N_values = as.numeric(.(.N)),
      wing_length_ind_base = mean(Wing.Length)
    ), by = .(scinam)]

  # merge and for missing values uppate means with those based on individual data
    v = merge(wsp, ws, all = TRUE)
    v[is.na(wing_length), wing_length := wing_length_ind_base]

  d = symerge(d, v[,.(scinam, wing_length)], sy)
  nrow(d[!is.na(wing_length)])

# add colour from Dale et al.
  names(co) = tolower(names(co))
  d <- symerge(d, co, sy)

# add colour from Cooney et al. 2022, Nature
  cooney = fread(here::here("Data/_cooney_2022.csv")) # single values per species and sex
  cooney[, scinam := tolower(Binomial)]
  cooney[, scinam := str_replace(scinam, '_', ' ')]
  cooney[, colourfulness := log10(LociUVS)]
  #setnames(cooney, "LociUVS", "colourfulness")
  cooney = cooney[, .(scinam, Sex, colourfulness)]
  cooney_w <- dcast(
    data = cooney,
    scinam ~ Sex,
    value.var = "colourfulness",
    fill = NA
  )
  setnames(cooney_w,
         old = c("F", "M"),
         new = c("colour_female", "colour_male"),
         skip_absent = TRUE)

  nrow(cooney_w)
  d <- symerge(d, cooney_w, sy)
  nrow(d[!is.na(colour_male)])

# PREPARE: SSD and colour dichromatism
  d[, SSD := log10(male_wing_length_g) - log10(female_wing_length_g)]
  d[, col_dimorph := male_plumage_score - female_plumage_score]
  d[, col_dimorph_cooney := colour_male - colour_female]

# add degree of polygyny (sexual_selection_intensity on males) from Dehley et al 2023, PNAS
  ssi <- fread(here::here("Data/_Delhey_et_al_2023_SexSelIntens_birdTreeTaxo.csv"), select = c(1, 2))
  setnames(ssi, c("scinam", "degree_of_polygyny"))
  d <- symerge(d, ssi, sy) # d2= merge(d, ssi, all.x = TRUE)
  #d[is.na(sexual_selection_intensity), scinam]

  #ssi2 <- fread("./Data/mating_system_BoW_taxo13may2021.csv", select = c(1, 5))
  #dssi2 <- symerge(d, ssi2, sy)
  #dssi2[is.na(sexual_selection_intensity), .(scinam)]
  #dss <- symerge(d, ss, sy)

# add habitat_breadth
  h <- fread(here::here("Data/_Ducatez_et_al_2024.txt"), select = c(1, 3)) # same as Seewiesen DB hab <- dbq(q = "SELECT scinam, habitat_breadth from AVES_environment.habitat_breadth")
  setnames(h, c("scinam", "habitat_breadth"))
  h[, scinam := tolower(str_replace(scinam, "-", " "))]
  d = symerge(d, h, sy) #works better than simple merge(d, h, all.x = TRUE) which give 116 NAs
  #d[.duplicates == TRUE]
  d[, i := 1:.N, scinam]
  d = d[i == 1][, i := NULL]
  d[, .duplicates := NULL]

# add migration (data from https://doi.org/10.1111/jbi.13700)
  d <- symerge(d, mig, sy)

# add sociality
  d <- symerge(d, soc, sy)

# add territoriality
  d <- symerge(d, ter, sy)

# add species richness (at the centre of the breeding range)
  con <- rmap_connect(path = here::here("Data/DAT_rangeMapper_all.sqlite")) # generated by DAT_rangeMapper.R
  SR <- stars::st_rasterize(rmap_to_sf(con, "species_richness") |>
    dplyr::select("species_richness", geometry))
  dbDisconnect(con)

  loc = st_as_sf(d[!is.na(lat), .(scinam, lat, lon)], coords = c("lon", "lat"), crs = projll) |>
    st_transform(projeck4)
  loc_SR = stars::st_extract(SR, loc) |> setDT()
  loc_SR = cbind(loc_SR[, .(species_richness)], d[!is.na(lat), .(scinam)])
  loc_SR[is.na(species_richness), species_richness := 1]
  #setnames(local_SR, "species_richness", "local_species_richness")

  d = merge(d, loc_SR, by = "scinam", all.x = TRUE)#, order = FALSE)

# add brain (for our own brain residuals, see toward the end)
  b <- read.xlsx(here::here"Data/_Sayol_et_al_2018_NatCom.xlsx"), cols = c(1, 5, 6, 7)) %>% data.table()
  setnames(b, c("scinam", "brain", "b_body", "brain_resid"))
  b[, scinam := tolower(str_replace(scinam, "_", " "))]
  b[scinam %in% 'acanthiza ewingii', b_body := 7]   # correct the body mass
  d <- symerge(d, b, sy)

  # add EPP
  epp <- fread(here::here("Data/_Valcu_et_al_2021_MolEcol.csv"))
  setnames(epp, 'scinam_birdtree', 'scinam')
  epp_sum = epp[, .(ep_broods = sum(ep_broods, na.rm = TRUE), wp_broods = sum(wp_broods, na.rm = TRUE), ep_offspring = sum(ep_offspring, na.rm = TRUE), wp_offspring = sum(wp_offspring, na.rm = TRUE)), by = scinam]
  epp_sum[, scinam := str_replace(scinam, '_', ' ')]
  d = merge(d, epp_sum[,.(scinam, ep_broods, wp_broods, ep_offspring, wp_offspring)], all.x = TRUE)

# add taxonomies
  f <- fread(here::here("Data/_families_eBird-sys3.txt"), select =1:2)
  #f <- read.xlsx("./DATA/_families_eBird_sy3.xlsx", cols = c(1, 2)) %>% data.table()
  #setnames(f, "use_fam_ebirdbw_final", "family")
  f[, family := firstup(family)]

  t <- fread(here::here("Data_higher_taxonomies.txt"), select =2:6)
  #t <- read.xlsx("./DATA/_families_&_higher_taxonomies.xlsx", cols = c(2:6)) %>% data.table()
  #setnames(t, "FINAL_family_USE_corrected_list3", "family")
  t[, family := firstup(family)]
  t[, superfamily := firstup(superfamily)]

  ft = merge(f, t, all.x = TRUE, sort = FALSE)
  ft[, scinam := tolower(scinam)]
  ft$suborder = NULL

  d[, genus := sub("\\ .*", "", scinam)]

  d <- symerge(d, ft, sy)

# PREPARE: scinam
  d[, scinam := str_replace(scinam, ' ', '_')]

# calculate our own brain residuals based on the brain and body mass data from Sayol et al. 2018, Nature Communications #d[!(is.na(brain) | is.na(b_body)), brain_r_our := resid(lm(log(brain) ~ log(b_body)))]
  d[!(is.na(brain) | is.na(b_body)), brain_r_our := resid(lmer(log(brain) ~ log(b_body) + (1 | infraorder / parvorder / superfamily / family / genus)))]

# EXPORT
  fwrite(d, here::here('Data/DAT_song_by_species.csv'), yaml = TRUE)

# number of complete cases (without brain)
  dd = copy(d)
  dd$brain = dd$b_body= dd$brain_resid = dd$brain_r_our = dd$ep_broods = dd$ep_offspring = NULL
  nrow(dd[complete.cases(dd)])
  dd$col_dimorph_cooney = dd$colour_male= dd$colour_female = NULL
  nrow(dd[complete.cases(dd)])
# END
