# ==========================================================================
# ❗This script is provided as reference only.
#  It uses tif tails of Copernicus Land Service continuous-field Tree Cover Fraction
#  raster (Version 2.0.1; Spatial Resolution: 100 meters; Epoch Year: 2015).
#  The script fixes coordinates, gathers tree-cover data from a published source
#  (see the manuscript for references), assigns percentage tree cover
#  to each recording in the raw_song.csv dataset and
#  exports DAT_tree_cover.csv to ./Data/.
# ==========================================================================

# Packages, settings (package sdb should be installed from https://github.com/ornitho-logics/sdb)

  source(here::here("R/__init__.R"))

  install_if_missing(
    c(
     "doSNOW", "dplyr", "exactextractr", "parallel",
     "raster", "units", "sf"
    ),
    extra_repos = c(r_universe = "https://cran.r-universe.dev"),
    github = c(dbo = "ornitho-logics/dbo")
  )

# load SONG
  x = fread("./Data/song_raw.csv")[!is.na(elements)]
  x = x[rec_quality_subj %in% c("A", "B")] # limit to high quality recordings (see manuscript for details)
  x[, id := .I]

# add missing geo-coordinates for recordings with valid location address
  x[, address := paste(site, country, sep = ",")]
  gc <- fread(here::here("Data/DAT_song_latlon_geocode.csv")) # generated by DAT_geocode_missing_XY.R
  # gc[address %in% gc[duplicated(address),address]]
  x <- merge(x, gc, by = "address", all.x = TRUE, sort = FALSE)
  x[is.na(latit), ":="(latit = lat, longit = long)]
  #x <- fread("./DATA/song_raw_prepared.csv")
  xx = x[!is.na(latit) & !is.na(longit)]
  xx[, lat := latit]
  xx[, lon := longit]

# GET: bounding box of each raster tile
  tree_cover_loc = '/Users/martinbulla/Dropbox/Science/DATA_collection/comparative/remote_sensing/Copernicus_Land_cover/data_source/tree_cover' # set the location of your tiles; the tiles are names as follows 'E000N00_ProbaV_LC100_epoch2015_global_v2.0.1_tree-coverfraction-layer_EPSG-4326.tif'

  squares =  data.table( fn = list.files(tree_cover_loc, full.names = TRUE) )
  squares[, i := .I]

  squares[, bnd := raster(fn) %>% extent %>% as(., 'SpatialPolygons') %>% st_as_sf , by = i]
  squares = st_as_sf(squares)  %>% st_buffer(dist = 0)

# ASSIGN: raster tile ID to each observation
  xs = st_intersection(st_as_sf(xx, coords = c('longit', 'latit') ), squares)
  setDT(xs)

# EXTRACT: % tree cover

## PASS 1 - extraction within ~100m buffer

### cluster
cl <- makeCluster(parallel::detectCores() - 7)
registerDoSNOW(cl)

### progress bar
pb <- txtProgressBar(min = 0, max = nrow(xs), style = 3)
progress <- function(n) setTxtProgressBar(pb, n)
opts <- list(progress = progress)

### loop
o1 <- foreach(i = seq_len(nrow(xs)), .combine = rbind,
              .packages = c("raster","sf","units","exactextractr","data.table"),
              .options.snow = opts, .errorhandling = "pass") %dopar% {

  xi  <- xs[i, ]
  ri  <- raster(xi$fn)

  spi <- st_as_sf(xi$geometry, crs = projection(ri)) %>%
    st_buffer(dist = set_units(0.001, "degree")) # 0.001 ~ 100-110m

  oi <- exactextractr::exact_extract(ri, spi)[[1]]
  np <- sum(!is.na(oi$value))
  val <- if (np == 0) NA_real_ else mean(oi$value, na.rm = TRUE)

  data.table(id = xi$id,
             perc_forest = val,
             npixels = np,
             radius_deg = if (np == 0) NA_real_ else 0.001)
}
close(pb)
stopCluster(cl)

### IDs to rescue
ids0 <- o1[npixels == 0, id]
length(ids0)  # 153


## PASS 2 - adaptive buffer only for the 153 recordings
### helper: adaptive extraction within one tile
extract_tc_adaptive <- function(ri, geom, radii_deg = c(0.001, 0.002, 0.005)) {
  for (d in radii_deg) {
    spi <- st_as_sf(geom, crs = projection(ri)) %>%
      st_buffer(dist = set_units(d, "degree"))

    oi <- exactextractr::exact_extract(ri, spi)[[1]]
    np <- sum(!is.na(oi$value))

    if (np > 0) {
      return(list(val = mean(oi$value, na.rm = TRUE), npixels = np, radius_deg = d))
    }
  }
  list(val = NA_real_, npixels = 0L, radius_deg = NA_real_)
}

### subset xs to only problematic IDs
xs2 <- xs[xs$id %in% ids0, ]
xs2 <- xs2[match(ids0, xs2$id), ]  # keep stable order by ids0

### cluster
cl <- makeCluster(parallel::detectCores() - 7)
registerDoSNOW(cl)

### progress bar
pb <- txtProgressBar(min = 0, max = nrow(xs2), style = 3)
progress <- function(n) setTxtProgressBar(pb, n)
opts <- list(progress = progress)

### loop
o2 <- foreach(i = seq_len(nrow(xs2)), .combine = rbind,
              .packages = c("raster","sf","units","exactextractr","data.table"),
              .options.snow = opts, .errorhandling = "pass") %dopar% {

  xi <- xs2[i, ]
  ri <- raster(xi$fn)

  res <- extract_tc_adaptive(ri, xi$geometry,
                            radii_deg = c(0.001, 0.002, 0.005, 0.02))  # choose your cap(s)

  data.table(id = xi$id,
             perc_forest = res$val,
             npixels = res$npixels,
             radius_deg = res$radius_deg)
}
close(pb)
stopCluster(cl)

### IDs to rescue
ids0_2 <- o2[npixels == 0, id]
length(ids0_2)  # 52

# UNITE: replace PASS-1 missing with PASS-2 results
o_final <- copy(o1)
setkey(o_final, id)
setkey(o2, id)
o_final[o2, `:=`(perc_forest = i.perc_forest,
                npixels = i.npixels,
                radius_deg = i.radius_deg)]

# EXPORT
X = xx[, .(lat, lon, id)]
X = merge(X, o_final[,.(perc_forest, id)], by = 'id', all.x = TRUE)
fwrite(X[!is.na(perc_forest)], here::here('Data/DAT_tree_cover.csv'))
